# Generated by Django 4.2.4 on 2023-08-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
    ]
